using Wms.Domain.Enums;

namespace Wms.Domain.Entities;

public sealed record ItemMasterDetails(
    string Name,
    string? LocalizedName = null,
    string? Description = null,
    string? LocalizedDescription = null,
    string? Category = null,
    string? Brand = null,
    string? ImageReference = null,
    string? DocumentReference = null,
    ItemType Type = ItemType.Stock,
    ItemLifecycleStatus LifecycleStatus = ItemLifecycleStatus.Active,
    string? PurchaseUnit = null,
    string? SalesUnit = null,
    decimal? NetWeightKg = null,
    decimal? LengthCm = null,
    decimal? WidthCm = null,
    decimal? HeightCm = null,
    decimal? VolumeCubicMeters = null,
    decimal? StandardCost = null,
    decimal? SalesPrice = null,
    string? CountryOfOrigin = null,
    string? CustomsCode = null,
    bool RequiresExpiry = false,
    bool UseFefo = false,
    bool QualityInspectionRequired = false,
    bool IsHazardous = false,
    bool TemperatureControlled = false,
    bool SpecialHandlingRequired = false,
    decimal? MinimumTemperatureCelsius = null,
    decimal? MaximumTemperatureCelsius = null,
    string? StorageProfile = null,
    string? PutawayProfile = null,
    string? DefaultSupplierCode = null,
    ItemReorderPolicy ReorderPolicy = ItemReorderPolicy.None,
    decimal? MinimumStock = null,
    decimal? MaximumStock = null,
    decimal? SafetyStock = null,
    int? LeadTimeDays = null,
    int ShelfLifeDays = 0,
    bool RequiresLot = false,
    bool RequiresSerial = false);
