using Wms.Application.Attachments;

namespace Wms.Infrastructure.Attachments;

/// <summary>
/// Development/local storage adapter. The key is generated by the application
/// and is resolved beneath the configured root; client file names never become
/// filesystem paths.
/// </summary>
public sealed class LocalAttachmentStorage(AttachmentStorageOptions options) : IAttachmentStorage
{
    public async Task StoreAsync(
        AttachmentStorageWrite write,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(write);
        var destination = ResolvePath(write.StorageKey);
        var directory = Path.GetDirectoryName(destination) ?? throw new IOException(
            "The attachment storage directory could not be resolved.");
        Directory.CreateDirectory(directory);

        var temporary = destination + "." + Guid.NewGuid().ToString("N") + ".tmp";
        try
        {
            await using (var output = new FileStream(
                temporary,
                FileMode.CreateNew,
                FileAccess.Write,
                FileShare.None,
                64 * 1024,
                FileOptions.Asynchronous | FileOptions.SequentialScan))
            {
                await write.Content.CopyToAsync(output, cancellationToken);
                if (output.Length != write.Length)
                {
                    throw new IOException("The stored attachment length did not match its metadata.");
                }

                await output.FlushAsync(cancellationToken);
                output.Flush(flushToDisk: true);
            }

            File.Move(temporary, destination, overwrite: false);
        }
        finally
        {
            TryDelete(temporary);
        }
    }

    public Task<Stream> OpenReadAsync(
        string storageKey,
        CancellationToken cancellationToken = default)
    {
        cancellationToken.ThrowIfCancellationRequested();
        var path = ResolvePath(storageKey);
        Stream stream = new FileStream(
            path,
            FileMode.Open,
            FileAccess.Read,
            FileShare.Read,
            64 * 1024,
            FileOptions.Asynchronous | FileOptions.SequentialScan);
        return Task.FromResult(stream);
    }

    public Task DeleteAsync(
        string storageKey,
        CancellationToken cancellationToken = default)
    {
        cancellationToken.ThrowIfCancellationRequested();
        var path = ResolvePath(storageKey);
        if (File.Exists(path))
        {
            File.Delete(path);
        }

        return Task.CompletedTask;
    }

    private string ResolvePath(string storageKey)
    {
        if (string.IsNullOrWhiteSpace(storageKey) ||
            Path.IsPathRooted(storageKey) ||
            storageKey.Contains('\\', StringComparison.Ordinal) ||
            storageKey.Contains("..", StringComparison.Ordinal))
        {
            throw new InvalidOperationException("The attachment storage key is invalid.");
        }

        var root = Path.GetFullPath(options.RootPath);
        var rootWithSeparator = root.EndsWith(Path.DirectorySeparatorChar)
            ? root
            : root + Path.DirectorySeparatorChar;
        var relative = storageKey.Replace('/', Path.DirectorySeparatorChar);
        var path = Path.GetFullPath(Path.Combine(root, relative));
        if (!path.StartsWith(rootWithSeparator, StringComparison.OrdinalIgnoreCase))
        {
            throw new InvalidOperationException("The attachment storage key escaped its root.");
        }

        return path;
    }

    private static void TryDelete(string path)
    {
        try
        {
            if (File.Exists(path))
            {
                File.Delete(path);
            }
        }
        catch
        {
            // The original storage exception is more useful to the caller.
        }
    }
}
